using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Effigy;

/// <summary>
/// Wavefront OBJ export — the DEBUG and interchange format, not the export path.
///
/// THIS IS NO LONGER HOW MODELS REACH s&amp;box. OBJ cannot carry bones or vertex weights, so it stops
/// being viable the moment a model is rigged, and rigging is in scope. SmdWriter is the export
/// path for both static and skinned models; see the note at the top of it for why one format
/// covers both.
///
/// What OBJ is still the best tool for, and why it stays:
///
///   It is the only format here that PRESERVES QUADS. SMD triangulates on the way out, so an OBJ is
///   the only way to look at the cage as the kernel actually holds it — which is exactly what you
///   need when checking whether a subdivision result is right. Open it in Blender and the topology
///   is there to read.
///
///   The test suite writes one per primitive for that reason, and round-trips them to prove the
///   writer emits something parseable with its topology intact.
///
/// Godot needs neither path — there the kernel hands vertices to ArrayMesh directly.
/// </summary>
public static class ObjWriter
{
	/// <summary>Kept as an alias so existing callers do not have to know where this moved to.</summary>
	public const float DefaultSmoothingAngleDegrees = MeshNormals.DefaultSmoothingAngleDegrees;

	/// <summary>What an unnamed slot is called. Shared with SmdWriter and DmxWriter so a model
	/// exported three ways names its materials the same three times.</summary>
	public static string DefaultMaterialName( int slot ) => $"material_{slot}";

	public static void WriteFile( PolyMesh mesh, string path, string objectName = "model",
		float smoothingAngleDegrees = DefaultSmoothingAngleDegrees, Func<int, string> materialName = null )
	{
		File.WriteAllText( path, Write( mesh, objectName, smoothingAngleDegrees, materialName ) );
	}

	/// <param name="materialName">What to call each material slot. Defaults to material_0, material_1
	/// and so on — a name a person chose is the difference between binding by meaning and binding by
	/// number in whatever the model lands in.</param>
	public static string Write( PolyMesh mesh, string objectName = "model",
		float smoothingAngleDegrees = DefaultSmoothingAngleDegrees, Func<int, string> materialName = null )
	{
		var sb = new StringBuilder();

		sb.Append( "# generated by Effigy\n" );
		sb.Append( $"# {mesh.VertexCount} vertices, {mesh.FaceCount} faces\n" );

		var offsets = (Vertices: 0, UVs: 0, Normals: 0);
		AppendPiece( sb, mesh, objectName, smoothingAngleDegrees, materialName, ref offsets );

		return sb.ToString();
	}

	/// <summary>
	/// Several named pieces in one file, each under its own <c>o</c> marker — which is what makes
	/// it come back as several parts rather than one welded lump.
	///
	/// THE MERGE IS THE LOSSY STEP, not the format. A part-segmentation export exists precisely so
	/// that a hand is a hand and a torso is a torso, and flattening fourteen of those into one mesh
	/// on the way out throws away the only thing that made the file worth segmenting: everything
	/// downstream that works per part — rigging a bone to a body, hiding one while you sculpt
	/// another, a Remesh with a budget of its own — has nothing left to work per part ON.
	///
	/// OBJ's indices are file-global rather than per-object, which is the entire reason this cannot
	/// be done by concatenating what <see cref="Write(PolyMesh, string, float, Func{int, string})"/>
	/// returns: every piece after the first would reference the first one's vertices.
	/// </summary>
	public static void WriteFile( IReadOnlyList<ObjReader.ObjPiece> pieces, string path,
		float smoothingAngleDegrees = DefaultSmoothingAngleDegrees, Func<int, string> materialName = null )
	{
		File.WriteAllText( path, Write( pieces, smoothingAngleDegrees, materialName ) );
	}

	/// <inheritdoc cref="WriteFile(IReadOnlyList{ObjReader.ObjPiece}, string, float, Func{int, string})"/>
	public static string Write( IReadOnlyList<ObjReader.ObjPiece> pieces,
		float smoothingAngleDegrees = DefaultSmoothingAngleDegrees, Func<int, string> materialName = null )
	{
		var sb = new StringBuilder();
		var offsets = (Vertices: 0, UVs: 0, Normals: 0);

		var vertices = 0;
		var faces = 0;

		foreach ( var piece in pieces )
		{
			vertices += piece.Mesh?.VertexCount ?? 0;
			faces += piece.Mesh?.FaceCount ?? 0;
		}

		sb.Append( "# generated by Effigy\n" );
		sb.Append( $"# {vertices} vertices, {faces} faces, {pieces.Count} objects\n" );

		for ( var i = 0; i < pieces.Count; i++ )
		{
			var piece = pieces[i];

			if ( piece.Mesh is null || piece.Mesh.FaceCount == 0 )
				continue;

			// An unnamed piece still needs a marker, or it merges into the one before it on the way
			// back in. ReadPieces hands back "" for faces that appeared before any o/g line.
			var name = string.IsNullOrWhiteSpace( piece.Name ) ? $"part_{i}" : piece.Name;

			AppendPiece( sb, piece.Mesh, name, smoothingAngleDegrees, materialName, ref offsets );
		}

		return sb.ToString();
	}

	/// <summary>One object's worth of the file. The offsets go in as the counts written so far and
	/// come back raised by this piece's own, because OBJ numbers v/vt/vn across the whole file.
	/// </summary>
	private static void AppendPiece( StringBuilder sb, PolyMesh mesh, string objectName,
		float smoothingAngleDegrees, Func<int, string> materialName,
		ref (int Vertices, int UVs, int Normals) offsets )
	{
		var c = CultureInfo.InvariantCulture;

		sb.Append( $"o {objectName}\n" );

		for ( var i = 0; i < mesh.Positions.Count; i++ )
		{
			var p = mesh.Positions[i];

			sb.Append( string.Format( c, "v {0:0.######} {1:0.######} {2:0.######}", p.x, p.y, p.z ) );

			// Vertex colour, when there is one. OBJ vertex colour is RGB, and "no paint" is WHITE —
			// the consumer multiplies the material by the colour, so white means "unchanged" and
			// coverage fades the vertex from white toward the paint colour.
			if ( mesh.VertexColors is not null && i < mesh.VertexColors.Length )
			{
				var tint = mesh.VertexColors[i].Tint();

				sb.Append( string.Format( c, " {0:0.######} {1:0.######} {2:0.######}",
					tint.x, tint.y, tint.z ) );
			}

			sb.Append( '\n' );
		}

		// UVs are per corner, so the same value recurs constantly. Deduping keeps the file to a
		// sane size without changing what it means.
		var uvIndex = new Dictionary<(long, long), int>();
		var faceUVRefs = new int[mesh.FaceCount][];

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			var f = mesh.Faces[fi];
			faceUVRefs[fi] = new int[f.Count];

			for ( var i = 0; i < f.Count; i++ )
			{
				var uv = f.UVs[i];

				// OBJ puts the UV origin at the bottom-left where Effigy's is top-left, so V is
				// flipped on the way out — the same flip FbxWriter makes for the same reason, and the
				// one DmxWriter avoids by leaving flipVCoordinates off and writing V as-is. Without it
				// a compiled static model samples its texture upside down relative to the viewport.
				var flippedV = 1f - uv.y;
				var key = ((long)MathF.Round( uv.x * 1e5f ), (long)MathF.Round( flippedV * 1e5f ));

				if ( !uvIndex.TryGetValue( key, out var idx ) )
				{
					idx = uvIndex.Count;
					uvIndex[key] = idx;
					sb.Append( string.Format( c, "vt {0:0.######} {1:0.######}\n", uv.x, flippedV ) );
				}

				faceUVRefs[fi][i] = idx;
			}
		}

		var (cornerNormals, normals) = MeshNormals.ComputeCornerNormals( mesh, smoothingAngleDegrees );

		foreach ( var n in normals )
			sb.Append( string.Format( c, "vn {0:0.######} {1:0.######} {2:0.######}\n", n.x, n.y, n.z ) );

		var currentMaterial = int.MinValue;

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			var f = mesh.Faces[fi];

			if ( f.Material != currentMaterial )
			{
				currentMaterial = f.Material;
				sb.Append( $"usemtl {(materialName ?? DefaultMaterialName)( currentMaterial )}\n" );
			}

			sb.Append( 'f' );

			for ( var i = 0; i < f.Count; i++ )
			{
				// OBJ indices are 1-based, and counted from the top of the FILE rather than from
				// the top of this object — hence the offsets, which are zero for a one-piece write.
				sb.Append( $" {f.Indices[i] + 1 + offsets.Vertices}"
					+ $"/{faceUVRefs[fi][i] + 1 + offsets.UVs}"
					+ $"/{cornerNormals[fi][i] + 1 + offsets.Normals}" );
			}

			sb.Append( '\n' );
		}

		offsets = (offsets.Vertices + mesh.VertexCount, offsets.UVs + uvIndex.Count,
			offsets.Normals + normals.Count);
	}

}

/// <summary>
/// Wavefront OBJ reader — the import path, and the round-trip for tests.
///
/// Understands what <see cref="ObjWriter"/> emits, plus the subset a Meshy or Blender export
/// actually uses: positions, optional vertex colour, UVs, faces (with or without vt/vn), and
/// <c>usemtl material_N</c>. Everything else on a line is ignored rather than refused, because
/// a real OBJ is full of <c>o</c> / <c>g</c> / <c>s</c> / <c>vn</c> / <c>mtllib</c> that do not
/// change the solid.
///
/// V IS FLIPPED, matching the writer. OBJ's UV origin is bottom-left; Effigy's is top-left.
/// Reading without the flip would import every textured mesh upside down, and a writer→reader
/// round trip would invert V twice and look correct by accident.
/// </summary>
public static class ObjReader
{
	public static PolyMesh ReadFile( string path ) => Read( File.ReadAllText( path ) );

	/// <summary>One named lump of an OBJ — an <c>o</c> object or a <c>g</c> group, with the faces
	/// that followed it. See <see cref="ReadPieces"/>.</summary>
	public readonly struct ObjPiece
	{
		public readonly string Name;
		public readonly PolyMesh Mesh;

		public ObjPiece( string name, PolyMesh mesh )
		{
			Name = name;
			Mesh = mesh;
		}
	}

	/// <summary>
	/// The whole file as one mesh, objects and groups fused. What every caller wanted before
	/// imports could be split, and what a writer's round-trip still compares against.
	/// </summary>
	public static PolyMesh Read( string text )
	{
		var parsed = Parse( text );
		var mesh = new PolyMesh { Positions = parsed.Positions };

		foreach ( var f in parsed.Faces )
			mesh.AddFace( f.Indices, f.UVs, f.Material );

		if ( parsed.SawColor )
			mesh.VertexColors = parsed.Colors.ToArray();

		return mesh;
	}

	/// <summary>
	/// The file split at its <c>o</c> and <c>g</c> lines, one mesh per lump.
	///
	/// WHY THIS EXISTS: an OBJ's vertex indices are global to the FILE, not to the object, so an
	/// exporter that carefully kept a character's eyelids, brows and hair as separate objects hands
	/// us one flat pile of triangles with the boundaries recorded only in these marker lines.
	/// Reading it with <see cref="Read"/> throws that structure away and produces one welded body —
	/// which is exactly the body you cannot build a tidy feature tree out of, and cannot hide,
	/// re-material or weight a piece of on its own.
	///
	/// Each piece gets its own vertex list, renumbered, holding only the vertices its faces
	/// actually use. Faces before the first marker land in a piece with an empty name; the caller
	/// decides what to call that, since only it knows what the file was called.
	///
	/// A file with no markers at all comes back as one unnamed piece, so a caller can always take
	/// this path rather than branching on whether the exporter bothered.
	/// </summary>
	public static List<ObjPiece> ReadPieces( string text )
	{
		var parsed = Parse( text );
		var pieces = new List<ObjPiece>();

		// Grouped by index rather than by name so two objects sharing a name stay two pieces —
		// a duplicated name is an exporter's business, not a reason to weld geometry together.
		var byGroup = new Dictionary<int, List<ObjFace>>();
		var order = new List<int>();

		foreach ( var f in parsed.Faces )
		{
			if ( !byGroup.TryGetValue( f.Group, out var list ) )
			{
				byGroup[f.Group] = list = new List<ObjFace>();
				order.Add( f.Group );
			}

			list.Add( f );
		}

		foreach ( var group in order )
		{
			var faces = byGroup[group];
			var mesh = new PolyMesh();
			var remap = new Dictionary<int, int>();
			var colors = parsed.SawColor ? new List<Vec4>() : null;

			foreach ( var f in faces )
			{
				var indices = new int[f.Indices.Length];

				for ( var i = 0; i < f.Indices.Length; i++ )
				{
					var source = f.Indices[i];

					if ( !remap.TryGetValue( source, out var local ) )
					{
						local = mesh.AddVertex( parsed.Positions[source] );
						remap[source] = local;
						colors?.Add( parsed.Colors[source] );
					}

					indices[i] = local;
				}

				mesh.AddFace( indices, f.UVs, f.Material );
			}

			if ( colors is not null )
				mesh.VertexColors = colors.ToArray();

			pieces.Add( new ObjPiece( group >= 0 ? parsed.GroupNames[group] : "", mesh ) );
		}

		return pieces;
	}

	readonly struct ObjFace
	{
		public readonly int[] Indices;
		public readonly Vec2[] UVs;
		public readonly int Material;
		public readonly int Group;

		public ObjFace( int[] indices, Vec2[] uvs, int material, int group )
		{
			Indices = indices;
			UVs = uvs;
			Material = material;
			Group = group;
		}
	}

	sealed class ObjData
	{
		public List<Vec3> Positions = new();
		public List<Vec4> Colors = new();
		public List<Vec2> UVs = new();
		public List<ObjFace> Faces = new();
		public List<string> GroupNames = new();
		public bool SawColor;
	}

	/// <summary>
	/// One pass over the text. Both readers above run on this, so a fused read and a split read
	/// cannot disagree about what the file says — which is the whole reason it is factored out
	/// rather than written twice.
	/// </summary>
	static ObjData Parse( string text )
	{
		var data = new ObjData();
		var material = 0;
		var group = -1;
		var c = CultureInfo.InvariantCulture;

		foreach ( var raw in text.Split( '\n' ) )
		{
			var line = raw.Trim();

			if ( line.Length == 0 || line[0] == '#' )
				continue;

			var parts = line.Split( ' ', StringSplitOptions.RemoveEmptyEntries );

			if ( parts.Length == 0 )
				continue;

			switch ( parts[0] )
			{
				case "v":
				{
					data.Positions.Add( new Vec3(
						float.Parse( parts[1], c ),
						float.Parse( parts[2], c ),
						float.Parse( parts[3], c ) ) );

					if ( parts.Length >= 7 )
					{
						data.SawColor = true;
						data.Colors.Add( new Vec4(
							float.Parse( parts[4], c ),
							float.Parse( parts[5], c ),
							float.Parse( parts[6], c ),
							1f ) );
					}
					else
					{
						data.Colors.Add( new Vec4( 1f, 1f, 1f, 1f ) );
					}

					break;
				}

				case "vt":
					// Writer flips V on the way out; this un-flips it. External OBJs (bottom-left
					// origin) land in Effigy space the same way.
					data.UVs.Add( new Vec2( float.Parse( parts[1], c ), 1f - float.Parse( parts[2], c ) ) );
					break;

				// BOTH MARKERS START A PIECE. Exporters disagree about which one means "object":
				// Blender writes `o` per object and `g` for its vertex groups, other tools only
				// ever write `g`. Treating either as a boundary is what makes the split work on
				// files this tool did not write, which is the only kind it gets.
				case "o":
				case "g":
					data.GroupNames.Add( parts.Length > 1 ? string.Join( " ", parts, 1, parts.Length - 1 ) : "" );
					group = data.GroupNames.Count - 1;
					break;

				case "usemtl":
					material = SlotFromMaterialName( parts.Length > 1 ? parts[1] : "", material );
					break;

				case "f":
				{
					var n = parts.Length - 1;

					if ( n < 3 )
						break;

					var indices = new int[n];
					var faceUVs = new Vec2[n];

					for ( var i = 0; i < n; i++ )
					{
						var refs = parts[i + 1].Split( '/' );
						indices[i] = ObjIndex( refs[0], data.Positions.Count, c );

						if ( refs.Length > 1 && refs[1].Length > 0 && data.UVs.Count > 0 )
							faceUVs[i] = data.UVs[ObjIndex( refs[1], data.UVs.Count, c )];
					}

					data.Faces.Add( new ObjFace( indices, faceUVs, material, group ) );
					break;
				}
			}
		}

		return data;
	}

	/// <summary>Wavefront indices are 1-based, and negative counts back from the last element.</summary>
	static int ObjIndex( string token, int count, CultureInfo c )
	{
		var n = int.Parse( token, c );
		return n > 0 ? n - 1 : count + n;
	}

	/// <summary><see cref="ObjWriter.DefaultMaterialName"/> is <c>material_N</c>; anything else
	/// leaves the current slot alone rather than inventing one.</summary>
	static int SlotFromMaterialName( string name, int current )
	{
		const string prefix = "material_";

		if ( name.StartsWith( prefix, StringComparison.OrdinalIgnoreCase )
			&& int.TryParse( name.AsSpan( prefix.Length ), NumberStyles.Integer, CultureInfo.InvariantCulture, out var slot )
			&& slot >= 0 )
			return slot;

		return current;
	}
}
