using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace ModelKernel;

/// <summary>
/// Wavefront OBJ export.
///
/// OBJ IS THE EXPORT TARGET BECAUSE s&box's ModelDoc IMPORTS IT — its documented source formats are
/// DMX, SMD, FBX, OBJ and VOX. OBJ is the only one of those that is plain text and writable in an
/// afternoon, so it is the cheapest route from this kernel to a real .vmdl: write the .obj, point a
/// RenderMeshFile node at it, compile.
///
/// It is also the fastest way to answer the open questions in MODELING-HANDOFF.md by running
/// something rather than reading something.
///
/// Godot does not need this path at all — there the kernel hands vertices to ArrayMesh directly.
/// The writer stays useful anyway as an interchange and debugging format: any OBJ written here
/// opens in Blender, which is the quickest way to see whether a subdivision result is actually
/// right.
/// </summary>
public static class ObjWriter
{
	/// <summary>Faces meeting at a sharper angle than this keep a hard edge; anything softer gets
	/// averaged. Without this a box comes out with rounded-looking corners and a cylinder comes out
	/// faceted — one threshold fixes both.</summary>
	public const float DefaultSmoothingAngleDegrees = 40f;

	public static void WriteFile( PolyMesh mesh, string path, string objectName = "model", float smoothingAngleDegrees = DefaultSmoothingAngleDegrees )
	{
		File.WriteAllText( path, Write( mesh, objectName, smoothingAngleDegrees ) );
	}

	public static string Write( PolyMesh mesh, string objectName = "model", float smoothingAngleDegrees = DefaultSmoothingAngleDegrees )
	{
		var sb = new StringBuilder();
		var c = CultureInfo.InvariantCulture;

		sb.Append( "# generated by ModelKernel\n" );
		sb.Append( $"# {mesh.VertexCount} vertices, {mesh.FaceCount} faces\n" );
		sb.Append( $"o {objectName}\n" );

		foreach ( var p in mesh.Positions )
			sb.Append( string.Format( c, "v {0:0.######} {1:0.######} {2:0.######}\n", p.x, p.y, p.z ) );

		// UVs are per corner, so the same value recurs constantly. Deduping keeps the file to a
		// sane size without changing what it means.
		var uvIndex = new Dictionary<(long, long), int>();
		var faceUVRefs = new int[mesh.FaceCount][];

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			var f = mesh.Faces[fi];
			faceUVRefs[fi] = new int[f.Count];

			for ( var i = 0; i < f.Count; i++ )
			{
				var uv = f.UVs[i];
				var key = ((long)MathF.Round( uv.x * 1e5f ), (long)MathF.Round( uv.y * 1e5f ));

				if ( !uvIndex.TryGetValue( key, out var idx ) )
				{
					idx = uvIndex.Count;
					uvIndex[key] = idx;
					sb.Append( string.Format( c, "vt {0:0.######} {1:0.######}\n", uv.x, uv.y ) );
				}

				faceUVRefs[fi][i] = idx;
			}
		}

		var (cornerNormals, normals) = ComputeCornerNormals( mesh, smoothingAngleDegrees );

		foreach ( var n in normals )
			sb.Append( string.Format( c, "vn {0:0.######} {1:0.######} {2:0.######}\n", n.x, n.y, n.z ) );

		var currentMaterial = int.MinValue;

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			var f = mesh.Faces[fi];

			if ( f.Material != currentMaterial )
			{
				currentMaterial = f.Material;
				sb.Append( $"usemtl material_{currentMaterial}\n" );
			}

			sb.Append( 'f' );

			for ( var i = 0; i < f.Count; i++ )
			{
				// OBJ indices are 1-based.
				sb.Append( $" {f.Indices[i] + 1}/{faceUVRefs[fi][i] + 1}/{cornerNormals[fi][i] + 1}" );
			}

			sb.Append( '\n' );
		}

		return sb.ToString();
	}

	/// <summary>
	/// One normal per face corner, averaged only across faces that agree to within the threshold.
	///
	/// The naive version — one averaged normal per vertex — rounds off every hard edge, so a box
	/// renders like a pillow. The other naive version — one normal per face — facets every curve,
	/// so a 32-segment cylinder looks like a nut. Thresholding gets both right from the same code
	/// and means the parametric stage never has to hand-author smoothing groups.
	/// </summary>
	static (int[][] CornerNormals, List<Vec3> Normals) ComputeCornerNormals( PolyMesh mesh, float angleDegrees )
	{
		var cosLimit = MathF.Cos( angleDegrees * MathF.PI / 180f );
		var faceNormals = new Vec3[mesh.FaceCount];
		var faceAreas = new float[mesh.FaceCount];

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			faceNormals[fi] = mesh.FaceNormal( mesh.Faces[fi] );
			faceAreas[fi] = mesh.FaceArea( mesh.Faces[fi] );
		}

		var vertexFaces = mesh.BuildVertexFaces();
		var normals = new List<Vec3>();
		var dedupe = new Dictionary<(long, long, long), int>();
		var cornerNormals = new int[mesh.FaceCount][];

		int Intern( Vec3 n )
		{
			var key = (
				(long)MathF.Round( n.x * 1e4f ),
				(long)MathF.Round( n.y * 1e4f ),
				(long)MathF.Round( n.z * 1e4f ));

			if ( dedupe.TryGetValue( key, out var idx ) )
				return idx;

			idx = normals.Count;
			normals.Add( n );
			dedupe[key] = idx;
			return idx;
		}

		for ( var fi = 0; fi < mesh.FaceCount; fi++ )
		{
			var f = mesh.Faces[fi];
			cornerNormals[fi] = new int[f.Count];

			for ( var i = 0; i < f.Count; i++ )
			{
				var sum = Vec3.Zero;

				foreach ( var other in vertexFaces[f.Indices[i]] )
				{
					if ( Vec3.Dot( faceNormals[fi], faceNormals[other] ) >= cosLimit )
						sum += faceNormals[other] * faceAreas[other];
				}

				var n = sum.Normal;

				// A degenerate cluster can cancel to zero; fall back to the face's own normal
				// rather than emitting (0,0,0), which some importers reject outright.
				if ( n.LengthSquared < 0.5f )
					n = faceNormals[fi];

				cornerNormals[fi][i] = Intern( n );
			}
		}

		return (cornerNormals, normals);
	}
}

/// <summary>
/// Minimal OBJ reader, for round-tripping in tests. Not a general importer — it understands only
/// what ObjWriter emits, which is exactly enough to prove the writer produces something parseable
/// with the counts and topology intact.
/// </summary>
public static class ObjReader
{
	public static PolyMesh Read( string text )
	{
		var mesh = new PolyMesh();
		var uvs = new List<Vec2>();
		var c = CultureInfo.InvariantCulture;

		foreach ( var raw in text.Split( '\n' ) )
		{
			var line = raw.Trim();

			if ( line.Length == 0 || line[0] == '#' )
				continue;

			var parts = line.Split( ' ', StringSplitOptions.RemoveEmptyEntries );

			switch ( parts[0] )
			{
				case "v":
					mesh.AddVertex( new Vec3(
						float.Parse( parts[1], c ),
						float.Parse( parts[2], c ),
						float.Parse( parts[3], c ) ) );
					break;

				case "vt":
					uvs.Add( new Vec2( float.Parse( parts[1], c ), float.Parse( parts[2], c ) ) );
					break;

				case "f":
				{
					var n = parts.Length - 1;
					var indices = new int[n];
					var faceUVs = new Vec2[n];

					for ( var i = 0; i < n; i++ )
					{
						var refs = parts[i + 1].Split( '/' );
						indices[i] = int.Parse( refs[0], c ) - 1;

						if ( refs.Length > 1 && refs[1].Length > 0 )
							faceUVs[i] = uvs[int.Parse( refs[1], c ) - 1];
					}

					mesh.AddFace( indices, faceUVs );
					break;
				}
			}
		}

		return mesh;
	}
}
