// Generated by Shader Forge.
//
// Description: glow
//
// Blocks:
//   Emissive Output — HDR emissive added to the surface
//
// This is a starting point, not finished art. Everything below is ordinary HLSL —
// edit it freely; Shader Forge never reads it back.

HEADER
{
	Description = "glow";
}

FEATURES
{
	#include "common/features.hlsl"
}

MODES
{
	Forward();
	Depth( S_MODE_DEPTH );
}

COMMON
{
	#include "common/shared.hlsl"

	// --- Emissive Output ---
	float3 g_vSfEmissiveColor < UiType( Color ); UiGroup( "Emissive Output,10/1" ); Attribute( "g_vSfEmissiveColor" ); Default3( 1.0, 0.65, 0.25 ); >;
	float g_flSfEmissiveStrength < UiGroup( "Emissive Output,10/2" ); Attribute( "g_flSfEmissiveStrength" ); Default( 2.0 ); Range( 0.0, 20.0 ); >;

	// Returns 1.0 unless a time-modulation block is in play, so any effect can
	// multiply by it unconditionally.
	float SFPulse()
	{
		return 1.0;
	}
}

struct VertexInput
{
	#include "common/vertexinput.hlsl"
};

struct PixelInput
{
	#include "common/pixelinput.hlsl"
};

VS
{
	#include "common/vertex.hlsl"

	PixelInput MainVs( VertexInput i )
	{
		PixelInput o = ProcessVertex( i );
		return FinalizeVertex( o );
	}
}

PS
{
	#include "common/pixel.hlsl"

	float4 MainPs( PixelInput i ) : SV_Target0
	{
		Material m = Material::From( i );

		// --- Emissive Output ---
		m.Emission += g_vSfEmissiveColor * g_flSfEmissiveStrength * SFPulse();

		float4 result = ShadingModelStandard::Shade( i, m );

		return result;
	}
}
