// Generated by Shader Forge.
//
// Description: glass
//
// Blocks:
//   Glass Material — Fresnel transparency with a tint and a polished surface
//
// This is a starting point, not finished art. Everything below is ordinary HLSL —
// edit it freely; Shader Forge never reads it back.

HEADER
{
	Description = "glass";
}

FEATURES
{
	#include "common/features.hlsl"
}

MODES
{
	Forward();
	Depth( S_MODE_DEPTH );
}

COMMON
{
	// Set before shared.hlsl - it selects the translucent render state.
	#define S_TRANSLUCENT 1

	#include "common/shared.hlsl"

	// --- Glass Material ---
	float g_flGlassOpacity < UiGroup( "Glass Material,10/1" ); Attribute( "g_flGlassOpacity" ); Default( 0.18 ); Range( 0.0, 1.0 ); >;
	float g_flGlassFresnel < UiGroup( "Glass Material,10/2" ); Attribute( "g_flGlassFresnel" ); Default( 3.0 ); Range( 0.5, 8.0 ); >;
	float3 g_vGlassTint < UiType( Color ); UiGroup( "Glass Material,10/3" ); Attribute( "g_vGlassTint" ); Default3( 0.85, 0.93, 1.0 ); >;
	float g_flGlassRoughness < UiGroup( "Glass Material,10/4" ); Attribute( "g_flGlassRoughness" ); Default( 0.08 ); Range( 0.0, 1.0 ); >;

	// Returns 1.0 unless a time-modulation block is in play, so any effect can
	// multiply by it unconditionally.
	float SFPulse()
	{
		return 1.0;
	}
}

struct VertexInput
{
	#include "common/vertexinput.hlsl"
};

struct PixelInput
{
	#include "common/pixelinput.hlsl"
};

VS
{
	#include "common/vertex.hlsl"

	PixelInput MainVs( VertexInput i )
	{
		PixelInput o = ProcessVertex( i );
		return FinalizeVertex( o );
	}
}

PS
{
	#include "common/pixel.hlsl"

	float3 SFViewDir( PixelInput i )
	{
		return normalize( g_vCameraPositionWs - i.vPositionWithOffsetWs.xyz );
	}

	float4 MainPs( PixelInput i ) : SV_Target0
	{
		Material m = Material::From( i );

		// --- Glass Material ---
		// Edge-on faces go opaque, face-on faces go clear - the whole reason glass reads as glass.
		float3 sfGlassView = SFViewDir( i );
		float sfGlassFacing = 1.0 - saturate( dot( normalize( i.vNormalWs ), sfGlassView ) );
		float sfGlassFresnel = pow( sfGlassFacing, g_flGlassFresnel );

		m.Albedo *= g_vGlassTint;
		m.Roughness = g_flGlassRoughness;
		m.Opacity = saturate( g_flGlassOpacity + sfGlassFresnel );

		float4 result = ShadingModelStandard::Shade( i, m );

		return result;
	}
}
