using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Marionette.ShaderForge;

/// <summary>
/// Assembles selected blocks into a complete .shader file in s&box's VFX wrapper format.
///
/// The skeleton is the engine's own minimal shader — HEADER / FEATURES / MODES / COMMON, the two
/// input structs, then VS and PS — with the blocks' snippets spliced into four points. Everything
/// outside those splice points is fixed, so a generated file differs from a hand-written one only
/// in the parts the blocks actually contributed.
///
/// Why parameters are declared in COMMON rather than PS: COMMON is included by both stages, and
/// vertex blocks (Wind, Water) need to read their own parameters. Declaring per-stage would mean
/// tracking which stage each parameter is used from and duplicating the ones used in both.
/// </summary>
public static class ShaderTemplate
{
	/// <summary>Where the generated shaders are written, relative to the project's Assets folder.</summary>
	public const string OutputFolder = "shaders/custom";

	/// <summary>
	/// The engine's shader source extension.
	///
	/// It is ".shader", NOT the ".shad" the design doc used. Writing .shad produced a file the
	/// asset pipeline never compiled, so the material system went looking for a .shader_c that
	/// nothing had produced and failed with ERROR_FILEOPEN. Assets/shaders/pixel_arms.shader is
	/// the working example in this repo.
	/// </summary>
	public const string Extension = ".shader";

	/// <summary>Filename the live preview material is written under. Always rewritten on tool
	/// open so the gated snippets stay in lockstep with the library.</summary>
	public const string LiveFileName = "shaderforge_live";

	/// <summary>Per-block on/off float the live preview uses. Typing a word flips this; no
	/// recompile.</summary>
	public static string EnableParam( string blockId ) => $"g_flSfOn_{blockId}";

	public static string Build( IReadOnlyList<ShaderBlock> blocks, string description )
	{
		var sb = new StringBuilder();

		var needsNoise = blocks.Any( b => b.NeedsNoise );
		var needsViewDir = blocks.Any( b => b.NeedsViewDir );
		var translucent = blocks.Any( b => b.NeedsTranslucent );
		var pulseBlock = blocks.FirstOrDefault( b => b.ProvidesPulse );

		// --- header -------------------------------------------------------------------------

		sb.AppendLine( "// Generated by Shader Forge." );
		sb.AppendLine( "//" );

		foreach ( var line in Wrap( $"Description: {Clean( description )}", 96 ) )
			sb.AppendLine( $"// {line}" );

		sb.AppendLine( "//" );
		sb.AppendLine( "// Blocks:" );

		foreach ( var block in blocks )
			sb.AppendLine( $"//   {block.Title} — {block.Summary}" );

		sb.AppendLine( "//" );
		sb.AppendLine( "// This is a starting point, not finished art. Everything below is ordinary HLSL —" );
		sb.AppendLine( "// edit it freely; Shader Forge never reads it back." );
		sb.AppendLine();

		sb.AppendLine( "HEADER" );
		sb.AppendLine( "{" );
		sb.AppendLine( $"\tDescription = \"{Clean( description )}\";" );
		sb.AppendLine( "}" );
		sb.AppendLine();

		// --- features -----------------------------------------------------------------------

		sb.AppendLine( "FEATURES" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/features.hlsl\"" );
		sb.AppendLine( "}" );
		sb.AppendLine();

		sb.AppendLine( "MODES" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\tForward();" );

		// Depth takes the mode define, matching Assets/shaders/pixel_arms.shader - the one shader
		// in this project known to compile.
		sb.AppendLine( "\tDepth( S_MODE_DEPTH );" );
		sb.AppendLine( "}" );
		sb.AppendLine();

		// --- common -------------------------------------------------------------------------

		sb.AppendLine( "COMMON" );
		sb.AppendLine( "{" );

		if ( translucent )
		{
			sb.AppendLine( "\t// Set before shared.hlsl - it selects the translucent render state." );
			sb.AppendLine( "\t#define S_TRANSLUCENT 1" );
			sb.AppendLine();
		}

		sb.AppendLine( "\t#include \"common/shared.hlsl\"" );
		sb.AppendLine();

		// Parameters, grouped per block so the material editor's UI groups match the blocks the
		// description asked for.
		foreach ( var block in blocks.Where( b => b.Params.Length > 0 ) )
		{
			sb.AppendLine( $"\t// --- {block.Title} ---" );

			foreach ( var declaration in block.Declarations() )
				sb.AppendLine( $"\t{declaration}" );

			sb.AppendLine();
		}

		if ( needsNoise )
		{
			sb.AppendLine( Indent( BlockLibrary.NoiseHelpers, 1 ) );
			sb.AppendLine();
		}

		// SFPulse is ALWAYS emitted, returning 1.0 when no time-modulation block was selected.
		// That is what lets any block multiply by it unconditionally.
		sb.AppendLine( "\t// Returns 1.0 unless a time-modulation block is in play, so any effect can" );
		sb.AppendLine( "\t// multiply by it unconditionally." );
		sb.AppendLine( "\tfloat SFPulse()" );
		sb.AppendLine( "\t{" );

		if ( pulseBlock is not null )
		{
			sb.AppendLine( "\t\tfloat wave = sin( g_flTime * g_flSfPulseSpeed * 6.2831853 ) * 0.5 + 0.5;" );
			sb.AppendLine( "\t\treturn 1.0 - g_flSfPulseDepth + g_flSfPulseDepth * wave;" );
		}
		else
		{
			sb.AppendLine( "\t\treturn 1.0;" );
		}

		sb.AppendLine( "\t}" );

		foreach ( var block in blocks.Where( b => !string.IsNullOrWhiteSpace( b.CommonCode ) ) )
		{
			sb.AppendLine();
			sb.AppendLine( Indent( block.CommonCode, 1 ) );
		}

		sb.AppendLine( "}" );
		sb.AppendLine();

		// --- input structs ------------------------------------------------------------------

		sb.AppendLine( "struct VertexInput" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/vertexinput.hlsl\"" );
		sb.AppendLine( "};" );
		sb.AppendLine();

		sb.AppendLine( "struct PixelInput" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/pixelinput.hlsl\"" );
		sb.AppendLine( "};" );
		sb.AppendLine();

		// --- vertex stage -------------------------------------------------------------------

		var vertexBlocks = blocks.Where( b => !string.IsNullOrWhiteSpace( b.VertexCode ) ).ToList();

		sb.AppendLine( "VS" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/vertex.hlsl\"" );
		sb.AppendLine();
		sb.AppendLine( "\tPixelInput MainVs( VertexInput i )" );
		sb.AppendLine( "\t{" );

		if ( vertexBlocks.Count > 0 )
		{
			// Displacement happens in object space BEFORE ProcessVertex, so the normals and
			// world transform it derives are computed from the displaced position.
			sb.AppendLine( "\t\tfloat3 vPositionOs = i.vPositionOs;" );

			foreach ( var block in vertexBlocks )
			{
				sb.AppendLine();
				sb.AppendLine( $"\t\t// --- {block.Title} ---" );
				sb.AppendLine( Indent( block.VertexCode.TrimEnd(), 1 ) );
			}

			sb.AppendLine();
			sb.AppendLine( "\t\ti.vPositionOs = vPositionOs;" );
			sb.AppendLine();
		}

		sb.AppendLine( "\t\tPixelInput o = ProcessVertex( i );" );
		sb.AppendLine( "\t\treturn FinalizeVertex( o );" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
		sb.AppendLine();

		// --- pixel stage --------------------------------------------------------------------

		var uvBlocks = blocks.Where( b => !string.IsNullOrWhiteSpace( b.UvCode ) ).ToList();
		var surfaceBlocks = blocks.Where( b => !string.IsNullOrWhiteSpace( b.SurfaceCode ) ).ToList();
		var postBlocks = blocks.Where( b => !string.IsNullOrWhiteSpace( b.PostCode ) ).ToList();

		sb.AppendLine( "PS" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/pixel.hlsl\"" );

		if ( needsViewDir )
		{
			sb.AppendLine();
			sb.AppendLine( Indent( BlockLibrary.ViewDirHelper, 1 ) );
		}

		sb.AppendLine();
		sb.AppendLine( "\tfloat4 MainPs( PixelInput i ) : SV_Target0" );
		sb.AppendLine( "\t{" );

		foreach ( var block in uvBlocks )
		{
			sb.AppendLine( $"\t\t// --- {block.Title} (uv warp, before the material is sampled) ---" );
			sb.AppendLine( Indent( block.UvCode.TrimEnd(), 1 ) );
			sb.AppendLine();
		}

		sb.AppendLine( "\t\tMaterial m = Material::From( i );" );

		foreach ( var block in surfaceBlocks )
		{
			sb.AppendLine();
			sb.AppendLine( $"\t\t// --- {block.Title} ---" );
			sb.AppendLine( Indent( block.SurfaceCode.TrimEnd(), 1 ) );
		}

		sb.AppendLine();
		sb.AppendLine( "\t\tfloat4 result = ShadingModelStandard::Shade( i, m );" );

		foreach ( var block in postBlocks )
		{
			sb.AppendLine();
			sb.AppendLine( $"\t\t// --- {block.Title} (after shading) ---" );
			sb.AppendLine( Indent( block.PostCode.TrimEnd(), 1 ) );
		}

		sb.AppendLine();
		sb.AppendLine( "\t\treturn result;" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );

		return sb.ToString();
	}

	/// <summary>
	/// One shader holding every library block, each gated by <see cref="EnableParam"/>. The live
	/// tool compiles this once, then typing a word is a Material.Set rather than a recompile —
	/// which is why "glowing" can light the sphere as you type it.
	/// </summary>
	public static string BuildLive( IReadOnlyList<ShaderBlock> blocks )
	{
		var sb = new StringBuilder();

		sb.AppendLine( "// Shader Forge live preview. Every library block is in here, gated off" );
		sb.AppendLine( "// until a word turns it on. Do not edit — the tool rewrites this on open." );
		sb.AppendLine();
		sb.AppendLine( "HEADER" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\tDescription = \"Shader Forge live preview\";" );
		sb.AppendLine( "}" );
		sb.AppendLine();
		sb.AppendLine( "FEATURES" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/features.hlsl\"" );
		sb.AppendLine( "}" );
		sb.AppendLine();
		sb.AppendLine( "MODES" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\tForward();" );
		sb.AppendLine( "\tDepth( S_MODE_DEPTH );" );
		sb.AppendLine( "}" );
		sb.AppendLine();
		sb.AppendLine( "COMMON" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/shared.hlsl\"" );
		sb.AppendLine();

		foreach ( var block in blocks )
		{
			sb.AppendLine( $"\tfloat {EnableParam( block.Id )} < UiGroup( \"Live,10/0\" ); Attribute( \"{EnableParam( block.Id )}\" ); Default( 0.0 ); Range( 0.0, 1.0 ); >;" );
		}

		sb.AppendLine();

		foreach ( var block in blocks.Where( b => b.Params.Length > 0 ) )
		{
			sb.AppendLine( $"\t// --- {block.Title} ---" );

			foreach ( var declaration in block.Declarations() )
				sb.AppendLine( $"\t{declaration}" );

			sb.AppendLine();
		}

		sb.AppendLine( Indent( BlockLibrary.NoiseHelpers, 1 ) );
		sb.AppendLine();
		sb.AppendLine( "\tfloat SFPulse()" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( $"\t\tif ( {EnableParam( "pulse" )} > 0.5 )" );
		sb.AppendLine( "\t\t{" );
		sb.AppendLine( "\t\t\tfloat wave = sin( g_flTime * g_flSfPulseSpeed * 6.2831853 ) * 0.5 + 0.5;" );
		sb.AppendLine( "\t\t\treturn 1.0 - g_flSfPulseDepth + g_flSfPulseDepth * wave;" );
		sb.AppendLine( "\t\t}" );
		sb.AppendLine();
		sb.AppendLine( "\t\treturn 1.0;" );
		sb.AppendLine( "\t}" );

		foreach ( var block in blocks.Where( b => !string.IsNullOrWhiteSpace( b.CommonCode ) ) )
		{
			sb.AppendLine();
			sb.AppendLine( Indent( block.CommonCode, 1 ) );
		}

		sb.AppendLine( "}" );
		sb.AppendLine();
		sb.AppendLine( "struct VertexInput" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/vertexinput.hlsl\"" );
		sb.AppendLine( "};" );
		sb.AppendLine();
		sb.AppendLine( "struct PixelInput" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/pixelinput.hlsl\"" );
		sb.AppendLine( "};" );
		sb.AppendLine();

		var vertexBlocks = blocks.Where( b => !string.IsNullOrWhiteSpace( b.VertexCode ) ).ToList();

		sb.AppendLine( "VS" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/vertex.hlsl\"" );
		sb.AppendLine();
		sb.AppendLine( "\tPixelInput MainVs( VertexInput i )" );
		sb.AppendLine( "\t{" );
		sb.AppendLine( "\t\tfloat3 vPositionOs = i.vPositionOs;" );

		foreach ( var block in vertexBlocks )
			Gated( sb, block, block.VertexCode, 2 );

		sb.AppendLine();
		sb.AppendLine( "\t\ti.vPositionOs = vPositionOs;" );
		sb.AppendLine( "\t\tPixelInput o = ProcessVertex( i );" );
		sb.AppendLine( "\t\treturn FinalizeVertex( o );" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
		sb.AppendLine();

		sb.AppendLine( "PS" );
		sb.AppendLine( "{" );
		sb.AppendLine( "\t#include \"common/pixel.hlsl\"" );
		sb.AppendLine();
		sb.AppendLine( Indent( BlockLibrary.ViewDirHelper, 1 ) );
		sb.AppendLine();
		sb.AppendLine( "\tfloat4 MainPs( PixelInput i ) : SV_Target0" );
		sb.AppendLine( "\t{" );

		foreach ( var block in blocks.Where( b => !string.IsNullOrWhiteSpace( b.UvCode ) ) )
			Gated( sb, block, block.UvCode, 2 );

		sb.AppendLine();
		sb.AppendLine( "\t\t// Init, not From: From samples the material's colour texture, and this" );
		sb.AppendLine( "\t\t// preview mesh has none — that is the red checkerboard. A solid albedo" );
		sb.AppendLine( "\t\t// is the clay; words paint on top of it." );
		sb.AppendLine( "\t\tMaterial m = Material::Init();" );
		sb.AppendLine( "\t\tm.Albedo = float3( 0.62, 0.63, 0.66 );" );
		sb.AppendLine( "\t\tm.Normal = normalize( i.vNormalWs.xyz );" );
		sb.AppendLine( "\t\tm.Roughness = 0.45;" );
		sb.AppendLine( "\t\tm.Metalness = 0.0;" );
		sb.AppendLine( "\t\tm.AmbientOcclusion = 1.0;" );
		sb.AppendLine( "\t\tm.Opacity = 1.0;" );
		sb.AppendLine( "\t\tm.Emission = float3( 0.0, 0.0, 0.0 );" );

		foreach ( var block in blocks.Where( b => !string.IsNullOrWhiteSpace( b.SurfaceCode ) ) )
			Gated( sb, block, block.SurfaceCode, 2 );

		sb.AppendLine();
		sb.AppendLine( "\t\tfloat4 result = ShadingModelStandard::Shade( i, m );" );

		foreach ( var block in blocks.Where( b => !string.IsNullOrWhiteSpace( b.PostCode ) ) )
			Gated( sb, block, block.PostCode, 2 );

		sb.AppendLine();
		sb.AppendLine( "\t\treturn result;" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );

		return sb.ToString();
	}

	private static void Gated( StringBuilder sb, ShaderBlock block, string code, int tabs )
	{
		if ( string.IsNullOrWhiteSpace( code ) )
			return;

		var pad = new string( '\t', tabs );

		sb.AppendLine();
		sb.AppendLine( $"{pad}// --- {block.Title} ---" );
		sb.AppendLine( $"{pad}if ( {EnableParam( block.Id )} > 0.5 )" );
		sb.AppendLine( $"{pad}{{" );
		sb.AppendLine( Indent( code.Trim(), tabs + 1 ) );
		sb.AppendLine( $"{pad}}}" );
	}

	/// <summary>Push a snippet in by whole tabs, preserving its own relative indentation. Blank
	/// lines stay blank rather than becoming lines of whitespace.</summary>
	private static string Indent( string code, int tabs )
	{
		var pad = new string( '\t', tabs );

		var lines = code.Replace( "\r\n", "\n" ).Split( '\n' )
			.Select( line => string.IsNullOrWhiteSpace( line ) ? "" : pad + line );

		return string.Join( Environment.NewLine, lines ).Trim( '\n', '\r' );
	}

	/// <summary>Strip anything that would break out of an HLSL string literal or a comment.</summary>
	private static string Clean( string text )
	{
		if ( string.IsNullOrWhiteSpace( text ) )
			return "Generated shader";

		var flattened = text.Replace( "\r", " " ).Replace( "\n", " " ).Replace( "\"", "'" );

		while ( flattened.Contains( "  " ) )
			flattened = flattened.Replace( "  ", " " );

		return flattened.Trim();
	}

	/// <summary>Wrap a comment to a column so long descriptions do not produce one enormous line.</summary>
	private static IEnumerable<string> Wrap( string text, int width )
	{
		var line = new StringBuilder();

		foreach ( var word in text.Split( ' ', StringSplitOptions.RemoveEmptyEntries ) )
		{
			if ( line.Length > 0 && line.Length + word.Length + 1 > width )
			{
				yield return line.ToString();
				line.Clear();
			}

			if ( line.Length > 0 )
				line.Append( ' ' );

			line.Append( word );
		}

		if ( line.Length > 0 )
			yield return line.ToString();
	}

	/// <summary>Turn a suggested name into something safe for a filename.</summary>
	public static string SafeFileName( string name )
	{
		if ( string.IsNullOrWhiteSpace( name ) )
			return "shader_forge_output";

		var builder = new StringBuilder( name.Length );

		foreach ( var c in name.ToLowerInvariant() )
			builder.Append( char.IsLetterOrDigit( c ) || c == '_' ? c : '_' );

		var cleaned = builder.ToString().Trim( '_' );

		return string.IsNullOrEmpty( cleaned ) ? "shader_forge_output" : cleaned;
	}
}
