#!/usr/bin/env python3
"""Catch the one editor mistake a compile cannot tell you about: a missing `using Editor;`.

WHY THIS EXISTS, AND WHY A BUILD DOES NOT REPLACE IT.

Editor code in this repo is often written without s&box in reach, and the check available in that
situation is to compile the editor sources against the kernel with the engine assemblies ABSENT.
That check cannot distinguish a missing `using` from a missing assembly - both are CS0246 - so a
single forgotten directive hides inside several hundred identical-looking errors. It has happened:
EffigyViewport.Sculpting.cs shipped without `using Editor;`, which left Widget, KeyEvent and
KeyCode unresolved and cascaded two more errors off the broken signatures, and it survived a
"compiles clean" claim because the 920 errors around it looked the same.

So: any file in the editor assembly that uses a type from the Editor namespace must import it.

WHAT THIS IS NOT. It is not a compiler and it does not know the Editor namespace - nothing here
can, with the engine absent. It carries a HAND-CURATED list of the Editor types this codebase
actually uses, below, and it only recognises them in positions where they can only be a type: a
static member access, a `new`, a base-type clause, a generic argument, a cast, or a declaration.
That restraint is deliberate. `Label` and `Frame` are Editor types AND ordinary property names in
this repo, so a bare name match would report every file and be turned off within a week.

When a new Editor type comes into use, add it. A name missing from the list is a case this does
not catch; a name wrongly on it is noise, which is worse.
"""

import os
import re
import sys

# The editor assembly. Editor/Effigy is the kernel MIRROR - engine-free by construction and
# generated by tools/sync-kernel.sh - so it is not editor code and must never import Editor.
ROOT = "Editor"
KERNEL_MIRROR = os.path.join("Editor", "Effigy")

# Types from the Editor namespace that this codebase uses. Curated; see the docstring.
EDITOR_TYPES = [
    # chrome and layout
    "Widget", "Layout", "DockWindow", "BaseWindow", "PopupWidget", "ScrollArea", "Splitter",
    "ToolBar", "StatusBar", "Frame", "Label", "Button", "IconButton", "LineEdit", "TextEdit",
    "ComboBox", "Checkbox", "Slider", "ColorPicker", "FileDialog", "ProgressBar", "Menu",
    "TreeView", "TreeNode", "Dialog", "ControlSheet", "ControlWidget", "PropertySheet",
    # painting and input
    "Paint", "Theme", "TextFlag", "ToolTip", "Pixmap", "CursorShape", "ScrollbarMode",
    "KeyEvent", "KeyCode", "MouseEvent", "WheelEvent", "DragEvent",
    # viewport and editor services
    "SceneRenderingWidget", "NativeRenderingWidget", "Gizmo", "EditorUtility", "EditorEvent",
    "EditorCookie", "ShortcutType", "Shortcut",
]

USING_EDITOR = re.compile(r"^\s*using Editor;\s*$", re.M)


def type_positions(name):
    """Patterns where `name` can only be a type, never a property or a local."""
    n = re.escape(name)
    return [
        (re.compile(r"\b" + n + r"\s*\."), "static member access"),
        (re.compile(r"\bnew\s+" + n + r"\b"), "construction"),
        (re.compile(r":\s*" + n + r"\b(?!\s*=)"), "base type"),
        (re.compile(r"<\s*" + n + r"\s*>"), "generic argument"),
        (re.compile(r"\(\s*" + n + r"\s*\)\s*\w"), "cast"),
        (re.compile(r"\b(?:public|private|protected|internal|override|virtual|static|readonly|"
                    r"out|ref|params)\s+(?:\w+\s+)*?" + n + r"\s+\w"), "declaration"),
    ]


PATTERNS = [(name, pattern, why) for name in EDITOR_TYPES for pattern, why in type_positions(name)]

# A line that is only a comment cannot be using a type. The prose in this repo names these types
# constantly - the docstring above would trip half the list - so comments are stripped first.
COMMENT = re.compile(r"^\s*(?://|/?\*|\*/)")


def is_kernel_mirror(directory):
    """Editor/Effigy only - NOT Editor/EffigyEditor, which is the thing this lint exists for.

    This was a plain startswith() and it silently skipped every Effigy editor file, because
    "Editor/EffigyEditor" starts with "Editor/Effigy". The lint reported a clean tree while
    checking barely half of it, which is the worst state a check can be in: it looks like
    evidence. Compare whole path components.
    """
    mirror = os.path.normpath(KERNEL_MIRROR)
    directory = os.path.normpath(directory)

    return directory == mirror or directory.startswith(mirror + os.sep)


def offences(path):
    with open(path, encoding="utf-8-sig") as handle:
        lines = handle.readlines()

    if USING_EDITOR.search("".join(lines)):
        return []

    found = []

    for number, line in enumerate(lines, start=1):
        if COMMENT.match(line):
            continue

        code = line.split("//", 1)[0]

        for name, pattern, why in PATTERNS:
            if pattern.search(code):
                found.append((number, name, why, line.strip()))
                break

    return found


def main():
    if not os.path.isdir(ROOT):
        print(f"no {ROOT}/ here - run this from the repo root", file=sys.stderr)
        return 2

    checked = 0
    failures = 0

    for directory, _, files in os.walk(ROOT):
        if is_kernel_mirror(directory):
            continue

        for name in sorted(files):
            if not name.endswith(".cs"):
                continue

            path = os.path.join(directory, name)
            checked += 1
            found = offences(path)

            if not found:
                continue

            failures += 1
            print(f"\n{path}: uses the Editor namespace and does not import it")
            print("  add `using Editor;` at the top, or fully qualify these:")

            for number, name_, why, text in found[:6]:
                print(f"    {path}:{number}  {name_} ({why})")
                print(f"      {text}")

            if len(found) > 6:
                print(f"    ... and {len(found) - 6} more")

    print(f"\n{checked} editor files checked, {failures} missing `using Editor;`")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
